/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sheetFraXcmBridgeSol from "./SheetFraXcmBridge.sol";
export type { sheetFraXcmBridgeSol };
export type { SheetFraRegistry } from "./SheetFraRegistry";
