/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SheetFraRegistry {
  export type SheetLinkStruct = {
    sheetHash: BytesLike;
    wallet: AddressLike;
    linkedAt: BigNumberish;
    active: boolean;
  };

  export type SheetLinkStructOutput = [
    sheetHash: string,
    wallet: string,
    linkedAt: bigint,
    active: boolean
  ] & { sheetHash: string; wallet: string; linkedAt: bigint; active: boolean };
}

export interface SheetFraRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACTION_APPROVE"
      | "ACTION_STAKE"
      | "ACTION_SWAP"
      | "ACTION_XCM"
      | "getLink"
      | "getWalletSheets"
      | "isLinked"
      | "linkSheet"
      | "links"
      | "owner"
      | "pause"
      | "paused"
      | "registerAction"
      | "renounceOwnership"
      | "totalLinks"
      | "transferOwnership"
      | "unlinkSheet"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "SheetActionRegistered"
      | "SheetLinked"
      | "SheetUnlinked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACTION_APPROVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_SWAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_XCM",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getLink", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getWalletSheets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isLinked", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "linkSheet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "links", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAction",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLinks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlinkSheet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ACTION_APPROVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_SWAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ACTION_XCM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLink", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWalletSheets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isLinked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "linkSheet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "links", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalLinks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlinkSheet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SheetActionRegisteredEvent {
  export type InputTuple = [
    sheetHash: BytesLike,
    wallet: AddressLike,
    actionHash: BytesLike,
    actionType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sheetHash: string,
    wallet: string,
    actionHash: string,
    actionType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    sheetHash: string;
    wallet: string;
    actionHash: string;
    actionType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SheetLinkedEvent {
  export type InputTuple = [
    sheetHash: BytesLike,
    wallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sheetHash: string,
    wallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sheetHash: string;
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SheetUnlinkedEvent {
  export type InputTuple = [
    sheetHash: BytesLike,
    wallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sheetHash: string,
    wallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sheetHash: string;
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SheetFraRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SheetFraRegistry;
  waitForDeployment(): Promise<this>;

  interface: SheetFraRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACTION_APPROVE: TypedContractMethod<[], [bigint], "view">;

  ACTION_STAKE: TypedContractMethod<[], [bigint], "view">;

  ACTION_SWAP: TypedContractMethod<[], [bigint], "view">;

  ACTION_XCM: TypedContractMethod<[], [bigint], "view">;

  getLink: TypedContractMethod<
    [sheetHash: BytesLike],
    [SheetFraRegistry.SheetLinkStructOutput],
    "view"
  >;

  getWalletSheets: TypedContractMethod<
    [wallet: AddressLike],
    [string[]],
    "view"
  >;

  isLinked: TypedContractMethod<[sheetHash: BytesLike], [boolean], "view">;

  linkSheet: TypedContractMethod<[sheetHash: BytesLike], [void], "nonpayable">;

  links: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        sheetHash: string;
        wallet: string;
        linkedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerAction: TypedContractMethod<
    [sheetHash: BytesLike, actionHash: BytesLike, actionType: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalLinks: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlinkSheet: TypedContractMethod<
    [sheetHash: BytesLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACTION_APPROVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ACTION_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ACTION_SWAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ACTION_XCM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLink"
  ): TypedContractMethod<
    [sheetHash: BytesLike],
    [SheetFraRegistry.SheetLinkStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWalletSheets"
  ): TypedContractMethod<[wallet: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isLinked"
  ): TypedContractMethod<[sheetHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "linkSheet"
  ): TypedContractMethod<[sheetHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "links"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        sheetHash: string;
        wallet: string;
        linkedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAction"
  ): TypedContractMethod<
    [sheetHash: BytesLike, actionHash: BytesLike, actionType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLinks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlinkSheet"
  ): TypedContractMethod<[sheetHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SheetActionRegistered"
  ): TypedContractEvent<
    SheetActionRegisteredEvent.InputTuple,
    SheetActionRegisteredEvent.OutputTuple,
    SheetActionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SheetLinked"
  ): TypedContractEvent<
    SheetLinkedEvent.InputTuple,
    SheetLinkedEvent.OutputTuple,
    SheetLinkedEvent.OutputObject
  >;
  getEvent(
    key: "SheetUnlinked"
  ): TypedContractEvent<
    SheetUnlinkedEvent.InputTuple,
    SheetUnlinkedEvent.OutputTuple,
    SheetUnlinkedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SheetActionRegistered(bytes32,address,bytes32,uint8,uint256)": TypedContractEvent<
      SheetActionRegisteredEvent.InputTuple,
      SheetActionRegisteredEvent.OutputTuple,
      SheetActionRegisteredEvent.OutputObject
    >;
    SheetActionRegistered: TypedContractEvent<
      SheetActionRegisteredEvent.InputTuple,
      SheetActionRegisteredEvent.OutputTuple,
      SheetActionRegisteredEvent.OutputObject
    >;

    "SheetLinked(bytes32,address,uint256)": TypedContractEvent<
      SheetLinkedEvent.InputTuple,
      SheetLinkedEvent.OutputTuple,
      SheetLinkedEvent.OutputObject
    >;
    SheetLinked: TypedContractEvent<
      SheetLinkedEvent.InputTuple,
      SheetLinkedEvent.OutputTuple,
      SheetLinkedEvent.OutputObject
    >;

    "SheetUnlinked(bytes32,address,uint256)": TypedContractEvent<
      SheetUnlinkedEvent.InputTuple,
      SheetUnlinkedEvent.OutputTuple,
      SheetUnlinkedEvent.OutputObject
    >;
    SheetUnlinked: TypedContractEvent<
      SheetUnlinkedEvent.InputTuple,
      SheetUnlinkedEvent.OutputTuple,
      SheetUnlinkedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
