/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SheetFraXcmBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "XCM"
      | "executeXcmMessage"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "weighXcmMessage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "XcmExecuteRequested"
      | "XcmWeighRequested"
  ): EventFragment;

  encodeFunctionData(functionFragment: "XCM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeXcmMessage",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "weighXcmMessage",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "XCM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeXcmMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "weighXcmMessage",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XcmExecuteRequestedEvent {
  export type InputTuple = [
    caller: AddressLike,
    operationId: BytesLike,
    sheetRef: string
  ];
  export type OutputTuple = [
    caller: string,
    operationId: string,
    sheetRef: string
  ];
  export interface OutputObject {
    caller: string;
    operationId: string;
    sheetRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XcmWeighRequestedEvent {
  export type InputTuple = [
    caller: AddressLike,
    refTime: BigNumberish,
    proofSize: BigNumberish,
    sheetRef: string
  ];
  export type OutputTuple = [
    caller: string,
    refTime: bigint,
    proofSize: bigint,
    sheetRef: string
  ];
  export interface OutputObject {
    caller: string;
    refTime: bigint;
    proofSize: bigint;
    sheetRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SheetFraXcmBridge extends BaseContract {
  connect(runner?: ContractRunner | null): SheetFraXcmBridge;
  waitForDeployment(): Promise<this>;

  interface: SheetFraXcmBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  XCM: TypedContractMethod<[], [string], "view">;

  executeXcmMessage: TypedContractMethod<
    [
      xcmMessage: BytesLike,
      maxRefTime: BigNumberish,
      maxProofSize: BigNumberish,
      operationId: BytesLike,
      sheetRef: string
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  weighXcmMessage: TypedContractMethod<
    [xcmMessage: BytesLike, sheetRef: string],
    [[bigint, bigint] & { refTime: bigint; proofSize: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "XCM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeXcmMessage"
  ): TypedContractMethod<
    [
      xcmMessage: BytesLike,
      maxRefTime: BigNumberish,
      maxProofSize: BigNumberish,
      operationId: BytesLike,
      sheetRef: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "weighXcmMessage"
  ): TypedContractMethod<
    [xcmMessage: BytesLike, sheetRef: string],
    [[bigint, bigint] & { refTime: bigint; proofSize: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "XcmExecuteRequested"
  ): TypedContractEvent<
    XcmExecuteRequestedEvent.InputTuple,
    XcmExecuteRequestedEvent.OutputTuple,
    XcmExecuteRequestedEvent.OutputObject
  >;
  getEvent(
    key: "XcmWeighRequested"
  ): TypedContractEvent<
    XcmWeighRequestedEvent.InputTuple,
    XcmWeighRequestedEvent.OutputTuple,
    XcmWeighRequestedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "XcmExecuteRequested(address,bytes32,string)": TypedContractEvent<
      XcmExecuteRequestedEvent.InputTuple,
      XcmExecuteRequestedEvent.OutputTuple,
      XcmExecuteRequestedEvent.OutputObject
    >;
    XcmExecuteRequested: TypedContractEvent<
      XcmExecuteRequestedEvent.InputTuple,
      XcmExecuteRequestedEvent.OutputTuple,
      XcmExecuteRequestedEvent.OutputObject
    >;

    "XcmWeighRequested(address,uint64,uint64,string)": TypedContractEvent<
      XcmWeighRequestedEvent.InputTuple,
      XcmWeighRequestedEvent.OutputTuple,
      XcmWeighRequestedEvent.OutputObject
    >;
    XcmWeighRequested: TypedContractEvent<
      XcmWeighRequestedEvent.InputTuple,
      XcmWeighRequestedEvent.OutputTuple,
      XcmWeighRequestedEvent.OutputObject
    >;
  };
}
